### ISSUE TITLE
Drop support for older python versions

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/sample-platform#757]
With the move to GCP complete, we should:
- Update our workflow to include newer Python version (3.10, 3.11)
- Drop support for older Python version (3.7), this blocks integration of #749 for example

**Comment by MatejMecka** [comment]
A dependency that is causing issues with python 3.10 is `githubpy==1.1.0`

```py
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kd/bsps7nbs01g8kznr9mtvn3m80000gn/T/pip-install-5t7ry3qc/githubpy_9ed59bb32ad74228a601fc5905689095/setup.py", line 4, in <module>
          import github
        File "/private/var/folders/kd/bsps7nbs01g8kznr9mtvn3m80000gn/T/pip-install-5t7ry3qc/githubpy_9ed59bb32ad74228a601fc5905689095/github.py", line 64, in <module>
          from collections import Iterable
      ImportError: cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
      [end of output]
```
It might need to be replaced with another library?

**Comment by Tarun-Arora** [comment]
@canihavesomecoffee @thealphadollar 
Since we are dropping support for older python versions, and upgrading to python 3.11, `nose` is no longer maintained..., so the testing framework needs to be changed as well...
We may use, Pytest: https://github.com/pytest-dev/pytest, suggestions?

**Comment by thealphadollar** [comment]
How about [nose2](https://github.com/nose-devs/nose2)?
